newsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("welcome.urls")),
    path("admin/", admin.site.urls, name="admin"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"

urlpatterns = [
    path("", views.start, name="start"),
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("mainpage/", views.mainpage, name="mainpage"),
    path("logout/", views.auth_logout, name="logout"),
    path("profileview/", views.profileview, name="profileview"),
    path("postcreate/", views.postcreate, name="postcreate"),
    path("postview/", views.postview, name="postview"),
    path("profileupdate/", views.profileupdate, name="profileupdate"),
    path("changepassword/", views.changepassword, name="changepassword"),
    path("search/", views.search, name="search"),
    path("friends/", views.friends, name="friends"),
    path(
        "sendfriendrequest/<int:userid>",
        views.send_friend_request,
        name="send_friend_request",
    ),
    path("accept_friend/<int:userid>", views.accept_friend, name="accept_friend"),
    path("userprofile/<int:profile_id>", views.userprofile, name="userprofile"),
    path("friendlist/", views.friend_list, name="friendlist"),
    path("remove_friend/<int:userid>", views.remove_friend, name="remove_friend"),
    path("cancel_request/<int:userid>", views.cancel_request, name="cancel_request"),
    path("friendsinvite/", views.friends_invites, name="friendsinvites"),
    path("mainpostview/", views.main_post_view, name="main_post_view"),
]

welcome/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

GENDER_CHOICES = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Not Specified", "Not Specified"),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.IntegerField(blank=True, null=True)
    dob = models.DateField(null=True, blank=True)
    dp = models.ImageField(upload_to="profile_pics")
    bio = models.CharField(max_length=300)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, default="Male")

    def __str__(self):
        return self.user.username


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})


status_choice = (
    ("A", "Accept"),
    ("S", "Sent"),
)


class Friendship(models.Model):
    status = models.CharField(max_length=50, choices=status_choice, blank=True)
    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receive", on_delete=models.CASCADE)

    def __str__(self):
        return "{} by {}".format(self.sender, self.receiver)

welcome/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class SearchForm(forms.Form):
    name = forms.CharField(label="Username", max_length=120)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'dp', 'gender', 'contact', 'dob']


class SignIn(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']



class PasswordForm(forms.ModelForm):
    new_password1 = forms.CharField(max_length=40)
    new_password2 = forms.CharField(max_length=40)

    class Meta:
        model = User
        fields = ["new_password1","new_password1"]



class SignUp(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)

    class Meta:
        model = User
        fields = [
            'username', 'email', 'first_name',
            'last_name', 'password1', 'password2'
        ]

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class PostForm(forms.ModelForm):
    # widget = forms.Textarea(
    #     attrs={'rows': 3,

    class Meta:
        model = Post
        fields = ['title', 'description']

welcome/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import PasswordForm, PostForm, ProfileForm, SignUp
from .models import Friendship, Post, Profile


def start(request):
    return render(request, "welcome/start.html")


def signup(request):
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            user = User.objects.get(username=username)
            new_profile = Profile(user=user)
            new_profile.save()
            messages.success(request, "User has been registered.")
            return redirect("/signin/")
    else:
        form = SignUp()
    return render(request, "welcome/signup.html", {"form": form})


@login_required()
def update_profile(request):
    same_user = request.user
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "welcome/profileupdate.html")
    context = {"user": same_user}
    return render(request, "welcome/mainpage.html", context)


def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/profileview/")
        else:
            return render(request, "welcome/signin.html", {"form": form})

    form = AuthenticationForm()
    return render(request, "welcome/signin.html", {"form": form})


@login_required()
def mainpage(request):
    return render(request, "welcome/mainpage.html")


@login_required()
def auth_logout(request):
    logout(request)
    return redirect("welcome:start")


@login_required()
def profileview(request):
    form = Profile(request.POST)
    context_list = Profile.objects.all()
    profile = Profile.objects.get(user=request.user)
    context_dict = {
        "context_list": context_list,
        "form": form,
        "profile": profile,
    }
    return render(request, "welcome/profileview.html", context_dict)


@login_required()
def changepassword(request):
    if request.method == "POST":
        new_password1 = request.POST.get("new_password1")
        new_password2 = request.POST.get("new_password2")
        if new_password1 == new_password2:
            user = User.objects.get(username=request.user.username)
            user.set_password(new_password1)
            user.save()
            return HttpResponse("Password changed")
        else:
            return HttpResponse("Wrong Password")

    else:
        form = PasswordForm()
        context = {"form": form}
        return render(request, "welcome/changepassword.html", context)


@login_required()
def profileupdate(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
        return redirect("/profileview/")
    form = ProfileForm(instance=request.user.profile)
    return render(request, "welcome/profileupdate.html", {"form": form})


@login_required()
def postcreate(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:postcreate")
    return render(request, "welcome/postcreate.html", {"form": form})


@login_required()
def main_post_view(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:main_post_view")

    sender = request.user
    friend = Q(sender=sender, status="Accept") | Q(receiver=sender, status="Accept")
    friends = Friendship.objects.filter(friend)
    friends_id = friends.values_list("sender__id", flat=True)
    self_id = friends.values_list("receiver__id", flat=True)

    allposts = Post.objects.all().order_by("-date_posted")
    context = {
        "allposts": allposts,
        "friends_id": friends_id,
        "self_id": self_id,
        "form": form,
    }
    return render(request, "welcome/mainpostview.html", context)


@login_required()
def postview(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:postview")
    allposts = Post.objects.all().order_by("-date_posted")
    return render(
        request, "welcome/postview.html", {"allposts": allposts, "form": form}
    )


@login_required()
def search(request):
    if request.method == "POST":
        query = request.POST.get("q")
        searcharea = Q(user__first_name__icontains=query) | Q(
            user__username__icontains=query
        )
        allprofile = Profile.objects.filter(searcharea)
        return render(request, "welcome/search.html", {"allprofile": allprofile})
    return render(request, "welcome/search.html")


@login_required()
def userprofile(request, profile_id):
    profile = Profile.objects.get(user_id=profile_id)
    try:
        context = Friendship.objects.get(
            sender=profile.user.id, receiver=request.user.id
        )
    except:
        context = Friendship.objects.filter(
            receiver=profile.user.id, sender=request.user.id
        )
    return render(
        request, "welcome/userprofile.html", {"profile": profile, "context": context}
    )


def friends(request):
    context = User.objects.all()
    check_status = Friendship.objects.all()
    return render(
        request,
        "welcome/friends.html",
        {"context": context, "check_status": check_status},
    )


@login_required()
def send_friend_request(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    friend_request, created = Friendship.objects.get_or_create(
        sender=sender, receiver=receiver, status="Sent"
    )
    if created:
        context = Profile.objects.all()
        return redirect(request.META.get("HTTP_REFERER", {"context": context}))
    else:
        context = Profile.objects.all()
        return redirect(request.META.get("HTTP_REFERER", {"context": context}))


@login_required()
def friends_invites(request):
    friend = Friendship.objects.filter(receiver=request.user, status="Sent")
    return render(request, "welcome/friendsinvite.html", {"friend": friend})


@login_required()
def accept_friend(request, userid):
    receiver = request.user
    sender = User.objects.get(id=userid)
    friend_request = Friendship.objects.get(sender=sender, receiver=receiver)
    friend_request.status = "Accept"
    friend_request.save()
    return render(request, "welcome/friendlist.html")


@login_required()
def friend_list(request):
    friendlist = Friendship.objects.filter(
        Q(sender=request.user, status="Accept")
        | Q(receiver=request.user, status="Accept")
    )
    return render(request, "welcome/friendlist.html", {"friendlist": friendlist})


@login_required()
def remove_friend(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    remove_friend = Friendship.objects.filter(
        Q(sender=sender, receiver=receiver, status="Accept")
        | Q(sender=receiver, receiver=sender, status="Accept")
    )
    remove_friend.delete()
    return redirect(request.META.get("HTTP_REFERER"))


@login_required()
def cancel_request(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    cancel_request = Friendship.objects.filter(
        Q(sender=sender, receiver=receiver, status="Sent")
        | Q(sender=receiver, receiver=sender, status="Sent")
    )
    cancel_request.delete()
    return redirect(request.META.get("HTTP_REFERER"))

welcome/templates/welcome/changepassword.html
{% extends 'base.html' %}

{% block head %}
    <title>Change Password</title>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="change-password-form">
            <h2>Change Your Password</h2>
            <form method="post" class="password-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Change Password</button>
            </form>
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/friendlist.html
{% extends 'base.html' %}

{% block head %}
    <title>Friends List</title>
{% endblock %}

{% block body %}
    <div class="container friends-list">
        {% for friend in friendlist %}
            <div class="friend-card">
                {% if friend.sender == request.user %}
                    <div class="friend-details">
                        <h2>{{ friend.receiver.first_name }} {{ friend.receiver.last_name }}</h2>
                        <span class="friend-count">{{ friend.receiver.count }}</span>
                        <h3><a href="{% url 'welcome:userprofile' friend.receiver_id %}">{{ friend.receiver }}</a></h3>
                        <a class="remove-friend-link" href="{% url 'welcome:remove_friend' userid=friend.receiver_id %}">
                            <button class="btn btn-danger">Remove Friend</button>
                        </a>
                    </div>
                {% else %}
                    <div class="friend-details">
                        <h2>{{ friend.sender.first_name }} {{ friend.sender.last_name }}</h2>
                        <h3><a href="{% url 'welcome:userprofile' friend.sender_id %}">{{ friend.sender }}</a></h3>
                        <a class="remove-friend-link" href="{% url 'welcome:remove_friend' userid=friend.sender_id %}">
                            <button class="btn btn-danger">Remove Friend</button>
                        </a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

welcome/templates/welcome/friends.html
{% extends 'base.html' %}
{% block head %}
    <title>Add friends</title>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Add friends</h1>
        <div class="container">
            <h3>{{ user.first_name }} {{ user.last_name }}</h3>
            <h4>Add Friends here</h4>
            {% csrf_token %}
            <form>
                {% for user in context %}
                    {% if user == request.user %}
                    {% else %}
                        <br>
                        {{ user.username|upper }}<br>
                            <a id="add" href="{% url 'welcome:send_friend_request'  userid=user.id %}" ><input type="button" value="Send Request" ></a> <br>
                            <a id="remove" href="{% url 'welcome:remove_friend'  userid=user.id %}"><input type="button" value='remove Friend'></a><br><br>

                    {% endif %}
                {% endfor %}
            </form>
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/friendsinvite.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Friend Invitations</title>
    <link rel="stylesheet" href="{% static 'css/friend-invites.css' %}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="friend-invites">
            {% for f in friend %}
                {% if f.sender != request.user %}
                    <div class="friend-card">
                        <div class="friend-details">
                            <h2>{{ f.sender.first_name.capitalize }} {{ f.sender.last_name.capitalize }}</h2>
                            <h4><a href="{% url 'welcome:userprofile' f.sender_id %}">{{ f.sender.username }}</a></h4>
                        </div>
                        <div class="friend-actions">
                            <a href="{% url 'welcome:accept_friend' userid=f.sender_id %}">
                                <button class="btn btn-accept">Accept Friend</button>
                            </a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/mainpostview.html
{% extends 'base.html' %}
{% block head %}
    <title>Show Posts</title>
    <style>
        .container {
            margin: 20px auto;
            width: 80%;
            max-width: 1000px;
        }

        .post-form {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
        }

        .blog {
            background-color: #298a8d;
            border: 1px solid #d1d1d1;
            padding: 20px;
            margin: 20px 0;
            border-radius: 10px;
        }

        .post-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
        }

        .post-title {
            font-size: 24px;
            margin: 0;
        }

        .post-user {
            color: #641783;
            text-decoration: none;
        }

        .post-description {
            font-size: 18px;
            margin-top: 10px;
        }

        .post-date {
            color: #6c757d;
            font-size: 14px;
        }
    </style>
{% endblock %}
{% block body %}
    <body>
    <div class="container">
        <form method="POST" action=" " class="post-form">
            {% csrf_token %} {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Post">
        </form>
    </div>
    <div class="container">
        {% for post in allposts %}
            {% if post.user_id in friends_id or post.user_id in self_id %}
                <div class="blog">
                    <div class="post-header">
                        <a class="post-user" href="{% url 'welcome:userprofile' post.user.id %}">
                            {{ post.user.username }}</a>
                        <span class="post-date">{{ post.date_posted }}</span>
                    </div>
                    <h2 class="post-title">{{ post.title }}</h2>
                    <p class="post-description">{{ post.description }}</p>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    </body>
{% endblock %}

welcome/templates/welcome/postcreate.html
{% extends 'base.html' %}
{% block head %}
    <title>create post</title>
{% endblock %}

{% block body %}
    <body>
    <div class="container">
        <h2>create post</h2>
        <form method="POST" action=" ">
            {% csrf_token %} {{ form.as_p }}
            <input type="submit" value="Post">
            <a href="welcome/postview.html"><input type="button" value="See Posts"></a><br>
        </form>
    </div>
    </body>
{% endblock %}

welcome/templates/welcome/postview.html
{% extends 'base.html' %}
{% block head %}
    <title>show post</title>

     <style>
.blog {
  background-color: #298a8d;
  width: 1000px;
  border: 15px solid lightblue;
  padding: 50px;
  margin: 20px;
}
</style>
{% endblock %}

{% block body %}
    <body>


    <div class="container">
        <form>
            {% csrf_token %}

            {% for post in allposts %}
            <div class="blog">
                <a href="{% url 'welcome:userprofile' post.user.id %}"><h4>{{ post.user.username }}</h4></a>
                <h4>{{ post.title }}</h4>
                <h3>{{ post.description }}</h3>
                <h6>{{ post.date_posted }}</h6>
            </div>
            {% endfor %}

        </form>
    </div>
    </body>

{% endblock %}

welcome/templates/welcome/profileupdate.html
{% extends 'base.html' %}
{% block head %}
    <title>Profile Update</title>
    <style>
        /* Additional styling specific to this template */
        .container {
            margin-top: 5px;
        }

        h2 {
            color: #007bff;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            margin-bottom: 10px;
        }

        input[type="text"],
        input[type="email"] {
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ced4da;
            border-radius: 5px;
            font-size: 16px;
        }

        button[type="submit"] {
            background-color: #007bff;
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block body %}
    <body>
    <div class="container">
        <h2>Update Your Profile</h2>
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Profile</button>
        </form>
    </div>
    </body>
{% endblock %}

welcome/templates/welcome/profileview.html
{% extends 'base.html' %}
{% block head %}
    <title>Profile View</title>
    <style>
        h1 {
            color: #007bff;
            margin-bottom: 20px;
        }
        img {
            display: block;
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            margin: 20px 0;
            box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1);
        }
        h3 {
            margin-top: 10px;
        }
        a {
            text-decoration: none;
            margin-top: 20px;
        }
        input[type="button"] {
            background-color: #007bff;
            color: #ffffff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }

        input[type="button"]:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>My Profile</h1>
        {% if profile.dp %}
            <img alt="Profile Picture" src="{{ profile.dp.url }}"
              width="300" height="300">
        {% endif %}
        <h3>Username: {{ profile.user }}</h3>
        <h3>Name: {{ user.first_name }} {{ user.last_name }}</h3>
        <h3>Email: {{ user.email }}</h3>
        <h3>Contact: {{ profile.contact }}</h3>
        <h3>DOB: {{ profile.dob }}</h3>
        <h3>Gender: {{ profile.gender }}</h3>
        <h3>Bio: {{ profile.bio }}</h3>
        <br>
        <p>Do you want to update your profile?
            <a href="/profileupdate"><input type="button" value="Update Profile"></a></p>
        <p>Do you want to see your friends?
            <a href="/friendlist"><input type="button" value="See Friend List"></a></p>
    </div>
{% endblock %}

welcome/templates/welcome/search.html
{% extends 'base.html' %}
{% block head %}
    <title>Search</title>
    <style>
        .profiles {
            background-color: lightgrey;
            width: 500px;
            border: 15px solid lightskyblue;
            padding: 20px;
            margin: 20px;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="q" placeholder="Search users">
            <input type="submit" value="Search">
        </form>
        <div class="container">
            {% for n in allprofile %}
                {% if n.user_id == request.user.id %}
                {% else %}
                    <div class="profiles">
                    {% if n.dp %}
                        <a href="{% url 'welcome:userprofile' n.user_id %}"><img
                                alt="" class="card-img-top"
                                src="{{ n.dp.url }}"
                                width="100" height="100"></a>
                    {% endif %}

                    <a href="{% url 'welcome:userprofile' n.user_id %}">{{ n.user.first_name.capitalize }} {{ n.user.last_name.capitalize }}</a>
                    <br><a href="{% url 'welcome:userprofile' n.user_id %}">{{ n.user.email }}</a>

                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/signin.html
{% extends 'base.html' %}
{% block head %}
    <title>Sign In</title>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="signin-container">
            <h2>Sign In</h2>
            <form method="POST" class="signin-form" action="">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary" type="submit">Sign In</button>
            </form>
            <p class="signup-link">Don't have an account? <a href="/signup">Create a new account</a></p>
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/signup.html
{% extends 'base.html' %}
{% block head %}
<title>Create a new account</title>
{% endblock %}
{% block body %}
<div class="container">
<h2>Create A New Account</h2>
{% block content %}
    <form method="POST" class="form-group" action="">
        {% csrf_token %}
        {{ form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit" class="btn btn-success">Register</button>
    </form>
    <a href="/signin"><input type="button" value="already a user"></a>
{% endblock %}
</div>
{% endblock %}

welcome/templates/welcome/start.html
{% extends 'base.html' %}

{% block head %}
    <title>Social Media Platform</title>
{% endblock %}

{% block body %}
    <div class="container">
        <header>
            <h1>Welcome to Our Social Network</h1>
        </header>
        <section class="content">
            <p>Connect, Share, and Engage with Friends</p>

        </section>
    </div>
{% endblock %}

welcome/templates/welcome/userprofile.html
{% extends 'base.html' %}
{% block head %}
    <title>Search Profile</title>
{% endblock %}

{% block body %}
    <div class="container">
        {% csrf_token %}
        {% if profile.dp %}
        <div class="mb-3">


            {% if context.status == 'Sent' %}
                <div>
                    {% if context.sender_id == request.user.id %}
                        <a href="{% url 'welcome:cancel_request'  userid=profile.user_id %}"><input
                            type="button" value="Cancel Request"></a> <br>


                    {% else %}
                        <a href="{% url 'welcome:accept_friend'  userid=profile.user_id %}"><input
                            type="button" value="Accept Friend"></a> <br>

                        </form>
                    {% endif %}
                        </div>

            {% endif %}

            {% if context.status == "Accept" %}

                    <a href="{% url 'welcome:remove_friend'  userid=profile.user_id %}"><input
                            type="button" value="Remove Friend"></a> <br>


            {% else %}
                    <a href="{% url 'welcome:send_friend_request'  userid=profile.user_id %}"><input
                            type="button" value="Send Request"></a> <br>

            {% endif %}

{#        /{{ context.receiver.id }}./{{ f.receiver_id }}..#}


                </div>
            {% endif %}


            <img alt="" class="card-img-top" src="{{ profile.dp.url }}"
                 width="300" height="300">


        <h2>{{ profile.bio }}</h2>
        <h3>Username: {{ profile.user }}</h3>
        <h3>
            Name: {{ profile.user.first_name }} {{ profile.user.last_name }}</h3>
        <h3>Email: {{ profile.user.email }}</h3>
        <h3>Contact: {{ profile.contact }}</h3>
        <h3>DOB: {{ profile.dob }}</h3>
        <h3>Gender: {{ profile.gender }}</h3>
        <h3>Bio: {{ profile.bio }}</h3>
    </div>
{% endblock %}