newsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("welcome.urls")),
    path("admin/", admin.site.urls, name="admin"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"

urlpatterns = [
    path("", views.start, name="start"),
    path("signin/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("mainpage/", views.mainpage, name="mainpage"),
    path("logout/", views.auth_logout, name="logout"),
    path("profileview/", views.profileview, name="profileview"),
    path("postcreate/", views.postcreate, name="postcreate"),
    path("postview/", views.postview, name="postview"),
    path("profileupdate/", views.profileupdate, name="profileupdate"),
    path("changepassword/", views.changepassword, name="changepassword"),
    path("search/", views.search, name="search"),
    path("friends/", views.friends, name="friends"),
    path(
        "sendfriendrequest/<int:userid>",
        views.send_friend_request,
        name="send_friend_request",
    ),
    path("accept_friend/<int:userid>", views.accept_friend, name="accept_friend"),
    path("userprofile/<int:profile_id>", views.userprofile, name="userprofile"),
    path("friendlist/", views.friend_list, name="friendlist"),
    path("remove_friend/<int:userid>", views.remove_friend, name="remove_friend"),
    path("cancel_request/<int:userid>", views.cancel_request, name="cancel_request"),
    path("friendsinvite/", views.friends_invites, name="friendsinvites"),
    path("mainpostview/", views.main_post_view, name="main_post_view"),
]

welcome/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

GENDER_CHOICES = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Not Specified", "Not Specified"),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.IntegerField(blank=True, null=True)
    dob = models.DateField(null=True, blank=True)
    dp = models.ImageField(upload_to="profile_pics")
    bio = models.CharField(max_length=300)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, default="Male")

    def __str__(self):
        return self.user.username


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})


status_choice = (
    ("A", "Accept"),
    ("S", "Sent"),
)


class Friendship(models.Model):
    status = models.CharField(max_length=50, choices=status_choice, blank=True)
    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receive", on_delete=models.CASCADE)

    def __str__(self):
        return "{} by {}".format(self.sender, self.receiver)

welcome/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class SearchForm(forms.Form):
    name = forms.CharField(label="Username", max_length=120)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'dp', 'gender', 'contact', 'dob']


class SignIn(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']



class PasswordForm(forms.ModelForm):
    new_password1 = forms.CharField(max_length=40)
    new_password2 = forms.CharField(max_length=40)

    class Meta:
        model = User
        fields = ["new_password1","new_password1"]



class SignUp(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=40)
    last_name = forms.CharField(max_length=40)

    class Meta:
        model = User
        fields = [
            'username', 'email', 'first_name',
            'last_name', 'password1', 'password2'
        ]

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class PostForm(forms.ModelForm):
    # widget = forms.Textarea(
    #     attrs={'rows': 3,

    class Meta:
        model = Post
        fields = ['title', 'description']

welcome/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import PasswordForm, PostForm, ProfileForm, SignUp
from .models import Friendship, Post, Profile


def start(request):
    return render(request, "welcome/start.html")


def signup(request):
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            user = User.objects.get(username=username)
            new_profile = Profile(user=user)
            new_profile.save()
            messages.success(request, "User has been registered.")
            return redirect("/signin/")
    else:
        form = SignUp()
    return render(request, "welcome/signup.html", {"form": form})


@login_required()
def update_profile(request):
    same_user = request.user
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "welcome/profileupdate.html")
    context = {"user": same_user}
    return render(request, "welcome/mainpage.html", context)


def signin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/profileview/")
        else:
            return render(request, "welcome/signin.html", {"form": form})

    form = AuthenticationForm()
    return render(request, "welcome/signin.html", {"form": form})


@login_required()
def mainpage(request):
    return render(request, "welcome/mainpage.html")


@login_required()
def auth_logout(request):
    logout(request)
    return redirect("welcome:start")


@login_required()
def profileview(request):
    form = Profile(request.POST)
    context_list = Profile.objects.all()
    profile = Profile.objects.get(user=request.user)
    context_dict = {
        "context_list": context_list,
        "form": form,
        "profile": profile,
    }
    return render(request, "welcome/profileview.html", context_dict)


@login_required()
def changepassword(request):
    if request.method == "POST":
        new_password1 = request.POST.get("new_password1")
        new_password2 = request.POST.get("new_password2")
        if new_password1 == new_password2:
            user = User.objects.get(username=request.user.username)
            user.set_password(new_password1)
            user.save()
            return HttpResponse("Password changed")
        else:
            return HttpResponse("Wrong Password")

    else:
        form = PasswordForm()
        context = {"form": form}
        return render(request, "welcome/changepassword.html", context)


@login_required()
def profileupdate(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
        return redirect("/profileview/")
    form = ProfileForm(instance=request.user.profile)
    return render(request, "welcome/profileupdate.html", {"form": form})


@login_required()
def postcreate(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:postcreate")
    return render(request, "welcome/postcreate.html", {"form": form})


@login_required()
def main_post_view(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:main_post_view")

    sender = request.user
    friend = Q(sender=sender, status="Accept") | Q(receiver=sender, status="Accept")
    friends = Friendship.objects.filter(friend)
    friends_id = friends.values_list("sender__id", flat=True)
    self_id = friends.values_list("receiver__id", flat=True)

    allposts = Post.objects.all().order_by("-date_posted")
    context = {
        "allposts": allposts,
        "friends_id": friends_id,
        "self_id": self_id,
        "form": form,
    }
    return render(request, "welcome/mainpostview.html", context)


@login_required()
def postview(request):
    form = PostForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            f1 = form.save(commit=False)
            f1.user = request.user
            f1.save()
        return redirect("welcome:postview")
    allposts = Post.objects.all().order_by("-date_posted")
    return render(
        request, "welcome/postview.html", {"allposts": allposts, "form": form}
    )


@login_required()
def search(request):
    if request.method == "POST":
        query = request.POST.get("q")
        searcharea = Q(user__first_name__icontains=query) | Q(
            user__username__icontains=query
        )
        allprofile = Profile.objects.filter(searcharea)
        return render(request, "welcome/search.html", {"allprofile": allprofile})
    return render(request, "welcome/search.html")


@login_required()
def userprofile(request, profile_id):
    profile = Profile.objects.get(user_id=profile_id)
    try:
        context = Friendship.objects.get(
            sender=profile.user.id, receiver=request.user.id
        )
    except:
        context = Friendship.objects.filter(
            receiver=profile.user.id, sender=request.user.id
        )
    return render(
        request, "welcome/userprofile.html", {"profile": profile, "context": context}
    )


def friends(request):
    context = User.objects.all()
    check_status = Friendship.objects.all()
    return render(
        request,
        "welcome/friends.html",
        {"context": context, "check_status": check_status},
    )


@login_required()
def send_friend_request(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    friend_request, created = Friendship.objects.get_or_create(
        sender=sender, receiver=receiver, status="Sent"
    )
    if created:
        context = Profile.objects.all()
        return redirect(request.META.get("HTTP_REFERER", {"context": context}))
    else:
        context = Profile.objects.all()
        return redirect(request.META.get("HTTP_REFERER", {"context": context}))


@login_required()
def friends_invites(request):
    friend = Friendship.objects.filter(receiver=request.user, status="Sent")
    return render(request, "welcome/friendsinvite.html", {"friend": friend})


@login_required()
def accept_friend(request, userid):
    receiver = request.user
    sender = User.objects.get(id=userid)
    friend_request = Friendship.objects.get(sender=sender, receiver=receiver)
    friend_request.status = "Accept"
    friend_request.save()
    return render(request, "welcome/friendlist.html")


@login_required()
def friend_list(request):
    friendlist = Friendship.objects.filter(
        Q(sender=request.user, status="Accept")
        | Q(receiver=request.user, status="Accept")
    )
    return render(request, "welcome/friendlist.html", {"friendlist": friendlist})


@login_required()
def remove_friend(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    remove_friend = Friendship.objects.filter(
        Q(sender=sender, receiver=receiver, status="Accept")
        | Q(sender=receiver, receiver=sender, status="Accept")
    )
    remove_friend.delete()
    return redirect(request.META.get("HTTP_REFERER"))


@login_required()
def cancel_request(request, userid):
    sender = request.user
    receiver = User.objects.get(id=userid)
    cancel_request = Friendship.objects.filter(
        Q(sender=sender, receiver=receiver, status="Sent")
        | Q(sender=receiver, receiver=sender, status="Sent")
    )
    cancel_request.delete()
    return redirect(request.META.get("HTTP_REFERER"))

welcome/templates/base.html
<html>
<head>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
        <title>Base</title>
    {% endblock %}
</head>
<body>
<br>
<div class="container">
    {#    <nav class="navbar navbar-default">#}
    {#    <nav class="navbar navbar-dark bg-primary">#}
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Social Network</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
{#                          <li><a href="{% url 'welcome:start' %}">Home</a></li>#}
                        <li>
                            <a href="{% url 'welcome:profileview' %}">Profile</a>
                        </li>
                        {#                        <li><a href="{% url 'welcome:mainpage' %}">Main Page</a></li>#}
{#                        <li><a href="{% url 'welcome:feed' %}">Feeds</a></li>#}
                        <li><a href="{% url 'welcome:main_post_view' %}">Feed</a></li>
                        <li><a href="{% url 'welcome:changepassword' %}">Change Password</a></li>
{#                        <li><a href="{% url 'welcome:friends' %}">Add Friends</a></li>#}
                        <li><a href="{% url 'welcome:search' %}">Search</a></li>
                        <li><a href="{% url 'welcome:friendlist' %}">Friend lists</a></li>
                        <li><a href="{% url 'welcome:friendsinvites' %}">Invites</a></li>


                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_superuser %}
                        <li><a href="   admin/">Admin</a></li>
                        <li><a href="{% url 'welcome:postview' %}">All Feed</a></li>

                        {% endif %}


                        <li><a href="{% url 'welcome:logout' %}">Log out</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'welcome:signin' %}">Login Here</a></li>
                        <li><a href="{% url 'welcome:signup' %}">Register</a>
                        </li>
                    </ul>
                {% endif %}
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>
</div>
{% block body %}
    <h1>Base</h1>
{% endblock %}
</body>
<script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</html>